---
- name: Create the ami
  hosts: localhost
  tasks:
  - import_role:
      name: openshift_aws
      tasks_from: build_ami.yml

# This is the part that installs all of the software and configs for the instance
# to become a node.
- import_playbook: ../../openshift-node/private/image_prep.yml
  vars:
    openshift_node_reboot_instance_before_cleanup: true

- import_playbook: seal_ami.yml
  vars:
    openshift_aws_ami_name: "openshift-gi-{{ lookup('pipe', 'date +%Y%m%d%H%M')}}"
