---
- name: create instance(s)
  ec2:
    assign_public_ip: yes
    count_tag:
      host-type: "{{ l_openshift_aws_instance }}"
    ebs_optimized: True
    exact_count: "{{ subnet_count_list[l_loop] }}"
    group_id: "{{ ec2sgs.security_groups | map(attribute='group_id') | list }}"
    instance_tags: "{{ instance_tags }}"
    instance_type: "{{ openshift_aws_instance_config[l_openshift_aws_instance].instance_type }}"
    image: "{{ image }}"
    key_name: "{{ openshift_aws_ssh_key_name }}"
    monitoring: False
    region: "{{ openshift_aws_region }}"
    termination_protection: False
    user_data: "{{ lookup('template', 'user_data.j2') }}"
    volumes: "{{ openshift_aws_instance_config[l_openshift_aws_instance].volumes }}"
    vpc_subnet_id: "{{ l_loop }}"
    wait: yes
  loop: "{{ subnet_count_list | list }}"
  loop_control:
    loop_var: l_loop
  retries: 3
  delay: 3
  register: ec2s
