---
- include_tasks: vpc_and_subnet_id.yml

- include_tasks: provision_instance_facts.yml
  with_items: "{{ l_instance_config }}"
  vars:
    l_instance_config: "{{ openshift_aws_instance_config }}"
  loop_control:
    loop_var: l_openshift_aws_instance
  when: "'master' in l_openshift_aws_instance"

- name: include master instance creation
  include_tasks: provision_instance.yml
  with_items: "{{ l_instance_config }}"
  vars:
    l_instance_config: "{{ openshift_aws_instance_config }}"
  loop_control:
    loop_var: l_openshift_aws_instance
  when: "'master' in l_openshift_aws_instance"

- name: fetch newly created instances
  ec2_instance_facts:
    region: "{{ openshift_aws_region }}"
    filters:
      "tag:clusterid": "{{ openshift_aws_clusterid }}"
      "tag:host-type": "master"
      instance-state-name: running
  register: instancesout
  retries: 20
  delay: 3
  until: instancesout.instances|length > 0

- name: include ec2 register
  include_tasks: elb_reg.yml
  loop: "{{ openshift_aws_elb_dict['master'] | dict2items }}"
  loop_control:
    loop_var: l_elb

- name: wait for ssh to become available
  wait_for:
    port: 22
    host: "{{ item.public_ip_address }}"
    timeout: 300
    search_regex: OpenSSH
  with_items: "{{ instancesout.instances }}"
  when: openshift_aws_wait_for_ssh | bool
